import { PlayerGameStats } from "../models";

export const mockGameStats: PlayerGameStats[] = [
  {
    playerId: "player1",
    playerName: "Jared Goff",
    position: "QB",
    manager: "Sean",
    passYards: 236,
    passTouchdowns: 3,
    interceptions: 0,
    rushAttempts: 2,
    rushYards: 0,
    rushTouchdowns: 1,
    receptions: 0,
    receivingYards: 0,
    receivingTouchdowns: 0,
    returnYards: 0,
    returnTouchdowns: 0,
    fumbleTouchdowns: 0,
    twoPoints: 0,
    lostFumbles: 0,
    totalPoints: 36.0,
  },
  {
    playerId: "player2",
    playerName: "Tony Pollard",
    position: "RB",
    manager: "Sean",
    passYards: 0,
    passTouchdowns: 0,
    interceptions: 0,
    rushAttempts: 8,
    rushYards: 29,
    rushTouchdowns: 0,
    receptions:4,
    receivingYards: 35,
    receivingTouchdowns: 0,
    returnYards: 0,
    returnTouchdowns: 0,
    fumbleTouchdowns: 0,
    twoPoints: 0,
    lostFumbles: 1,
    totalPoints: 8.2
  },
];
